// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc7913.Test1.subsystems;


import edu.wpi.first.wpilibj.*;
import org.usfirst.frc7913.Test1.Robot;
import org.usfirst.frc7913.Test1.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Hatch extends Subsystem {
    private Compressor compressor;
    private DoubleSolenoid hatchPiston;
    private Solenoid openPiston;
    private Solenoid closePiston;

    public Hatch() {
        compressor = new Compressor(0);
        addChild("compressor",compressor);
        
        
        hatchPiston = new DoubleSolenoid(0, 0, 1);
        addChild("hatchPiston",hatchPiston);

        openPiston = new Solenoid(7);
        closePiston = new Solenoid(6);

    }

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new retractPiston());
    }

    @Override
    public void periodic() {

    }

    public void extend(){
        Robot.hatch.hatchPiston.set(Value.kForward);
    }
    public void retract(){
        Robot.hatch.hatchPiston.set(Value.kReverse);
    }

    public void openPistonOn(){
        Robot.hatch.openPiston.set(true);
    }

    public void openPistonOff(){
        Robot.hatch.openPiston.set(false);
    }

    public void closePistonOn(){
        Robot.hatch.closePiston.set(true);
    }

    public void closePistonOff(){
        Robot.hatch.closePiston.set(false);
    }
}
    
